title: Ze Jin
description: Post Knowledge & Experience!
theme: just-the-docs

url: https://zej97.github.io
math: katex
google_analytics: G-D76HN0NQCW
favicon_ico: /assets/images/favicon.ico
color_scheme: dark